# coding: utf-8

# SPDX-FileCopyrightText: 2023 Ledger SAS
# SPDX-License-Identifier: LicenseRef-LEDGER
"""template version file."""

# PlaceHolder for automatic build tools versioning, DO NOT EDIT this file !!!

__version__ = "0.0.0"
